### ISSUE TITLE
It would be nice if holding down Shift would cause page up/down stepping

### ISSUE THREAD

**Issue by philipag** [amit115532/SmoothScrolling#2]
Some other smooth scroll implementations support this and it would be nice

**Comment by amit115532** [comment]
Fixed!

**Comment by philipag** [comment]
Sorry I was not clear enough.  I just installed the updated Nuget but it does not do what I meant.

The shift key should not bypass Smooth Scrolling.  Instead, it should cause smoothscroll to move further per mouse wheel tick. Ideally each scroll wheel step - no matter the size since different mice will have different step size - would jump exactly one page.  This would make it very quick to get the equivalent of page up/down without leaving the mouse.

Anyway this is just a nicety and not absolutely essential.

**Comment by amit115532** [comment]
Alright, working on it.

**Comment by amit115532** [comment]
Feature implemented, added an option to define the alternative scrolling intensity when pressing shift.
Also kept the option to shut down this option
